revert verify changes

diff --git a/.github/workflows/maven-docker-verify-job.yml b/.github/workflows/maven-docker-verify-job.yml
--- a/.github/workflows/maven-docker-verify-job.yml
+++ b/.github/workflows/maven-docker-verify-job.yml
@@ -64,4 +64,15 @@ jobs:
 
     steps:
     - name: Build with Maven
-      run: sh ./verify-image.sh
+      run: |
+        docker run -d --name test -p 8080:8080 ghcr.io/USERNAME/cubix/1/homework/app:springboot > /dev/null
+        sleep 10
+        curl --fail http://localhost:8080/cubix/test
+        RESULT=$?
+        if [ $RESULT -ne 0 ]; then
+          echo "Verification failed, here are the logs"
+          docker logs test
+        fi
+        docker stop test > /dev/null
+        docker rm test > /dev/null
+        exit $RESULT
